"use client";

import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Loader2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { vehicleApi } from "@/lib/api/vehicle-api";
import type { VehicleInput, VehicleType } from "@/lib/api/api-types";
import { getApiErrorMessage } from "@/lib/api/api-error";
import { queryKeys } from "@/lib/query-keys";

export function VehicleEditDialog({ vehicleId, onClose }: { vehicleId: string | null; onClose: () => void }) {
  const client = useQueryClient(); const query = useQuery({ queryKey: queryKeys.vehicles.detail(vehicleId ?? ""), queryFn: () => vehicleApi.detail(vehicleId!), enabled: Boolean(vehicleId) });
  const update = useMutation({ mutationFn: (input: Partial<Omit<VehicleInput, "isDefault">>) => vehicleApi.update(vehicleId!, input), onSuccess: async (vehicle) => { client.setQueryData(queryKeys.vehicles.detail(vehicle.id), vehicle); await client.invalidateQueries({ queryKey: queryKeys.vehicles.all }); onClose(); } });
  function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); const number = (name: string) => { const value = String(data.get(name) ?? ""); return value ? Number(value) : undefined; }; update.mutate({ vehicleType: String(data.get("vehicleType")) as VehicleType, registrationNumber: String(data.get("registrationNumber")), brand: String(data.get("brand")), model: String(data.get("model")), color: String(data.get("color")), heightCm: number("heightCm"), widthCm: number("widthCm"), lengthCm: number("lengthCm") }); }
  const item = query.data;
  return <Dialog open={Boolean(vehicleId)} onOpenChange={(open) => { if (!open && !update.isPending) onClose(); }}><DialogContent><DialogHeader><DialogTitle>Vehicle details</DialogTitle><DialogDescription>These fields are loaded from and saved to the Vehicle API.</DialogDescription></DialogHeader>{query.isPending ? <div className="p-8 text-center"><Loader2 className="mx-auto size-5 animate-spin" /></div> : query.isError ? <p role="alert" className="text-sm text-red-700">{getApiErrorMessage(query.error)}</p> : item && <form key={item.updatedAt} onSubmit={submit} className="grid gap-4 sm:grid-cols-2"><label className="space-y-1 text-sm font-semibold">Vehicle type<select name="vehicleType" className="h-10 w-full rounded-lg border bg-white px-3 font-normal" defaultValue={item.vehicleType}><option value="MOTORCYCLE">Motorcycle</option><option value="SEDAN">Sedan</option><option value="SUV">SUV</option><option value="MICROBUS">Microbus</option></select></label><Field name="registrationNumber" label="Registration number" defaultValue={item.registrationNumber} /><Field name="brand" label="Brand" defaultValue={item.brand} /><Field name="model" label="Model" defaultValue={item.model} /><Field name="color" label="Color" defaultValue={item.color} /><Field name="heightCm" label="Height (cm)" type="number" defaultValue={item.heightCm ?? ""} /><Field name="widthCm" label="Width (cm)" type="number" defaultValue={item.widthCm ?? ""} /><Field name="lengthCm" label="Length (cm)" type="number" defaultValue={item.lengthCm ?? ""} />{update.isError && <p role="alert" className="text-sm text-red-700 sm:col-span-2">{getApiErrorMessage(update.error)}</p>}<DialogFooter className="sm:col-span-2"><Button type="button" variant="outline" onClick={onClose}>Cancel</Button><Button type="submit" disabled={update.isPending}>{update.isPending ? <Loader2 className="size-4 animate-spin" /> : "Save vehicle"}</Button></DialogFooter></form>}</DialogContent></Dialog>;
}
function Field({ name, label, defaultValue, type = "text" }: { name: string; label: string; defaultValue: string | number; type?: string }) { const id = `vehicle-${name}`; return <div className="space-y-1"><Label htmlFor={id}>{label}</Label><Input id={id} name={name} type={type} min={type === "number" ? 1 : undefined} max={type === "number" ? 10000 : undefined} defaultValue={defaultValue} required={type !== "number"} /></div>; }
