"use client";

import { useMemo, useState } from "react";
import Link from "next/link";
import { Building2, Loader2, MapPin, Plus, RefreshCw, Search } from "lucide-react";
import { OwnerHeader } from "@/components/owner/owner-header";
import { Button } from "@/components/ui/button";
import { useProperties } from "@/hooks/use-properties";
import { getApiErrorMessage } from "@/lib/api/api-error";

export function OwnerPropertiesLiveView() {
  const { query } = useProperties(); const [search, setSearch] = useState(""); const properties = useMemo(() => (query.data ?? []).filter((item) => `${item.name} ${item.publicArea} ${item.approximateAddress}`.toLowerCase().includes(search.toLowerCase())), [query.data, search]);
  return <div className="min-h-full"><OwnerHeader title="My Properties" subtitle="Manage the Properties where you provide parking." actions={<Link href="/owner/properties/new" className="inline-flex items-center gap-2 rounded-lg bg-[#064E3B] px-4 py-2 text-xs font-bold text-white"><Plus className="size-4" />Add property</Link>} /><div className="mx-auto max-w-7xl space-y-6 p-6 sm:p-8"><div className="relative max-w-xl"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-slate-400" /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search properties" className="h-11 w-full rounded-xl border bg-white pl-10 pr-4 text-sm outline-none focus:border-emerald-700" /></div>{query.isPending && <State><Loader2 className="mx-auto size-6 animate-spin" /><p className="mt-2">Loading properties…</p></State>}{query.isError && <State><p className="text-red-700">{getApiErrorMessage(query.error)}</p><Button className="mt-4" variant="outline" onClick={() => query.refetch()}><RefreshCw className="size-4" />Retry</Button></State>}{!query.isPending && !query.isError && properties.length === 0 && <State><Building2 className="mx-auto size-8 text-emerald-700" /><p className="mt-3 font-semibold">No matching properties</p><p className="mt-1 text-xs text-slate-500">Create a Property to start the backend-supported verification flow.</p></State>}<div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{properties.map((property) => <Link key={property.id} href={`/owner/properties/${property.id}`} className="rounded-2xl border bg-white p-5 shadow-sm transition hover:-translate-y-0.5 hover:shadow-md"><div className="flex items-start justify-between gap-3"><span className="flex size-11 items-center justify-center rounded-xl bg-emerald-50 text-[#064E3B]"><Building2 className="size-5" /></span><div className="flex gap-1"><span className="rounded-full bg-slate-100 px-2 py-1 text-[9px] font-bold">{property.status.replaceAll("_", " ")}</span><span className={`rounded-full px-2 py-1 text-[9px] font-bold ${property.verificationStatus === "VERIFIED" ? "bg-emerald-100 text-emerald-800" : property.verificationStatus === "REJECTED" ? "bg-red-100 text-red-800" : "bg-amber-100 text-amber-800"}`}>{property.verificationStatus}</span></div></div><h2 className="mt-4 font-bold text-slate-900">{property.name}</h2><p className="mt-2 flex gap-2 text-xs text-slate-500"><MapPin className="size-4 shrink-0" />{property.approximateAddress}</p>{property.rejectionReason && <p className="mt-3 rounded-lg bg-red-50 p-2 text-xs text-red-700">{property.rejectionReason}</p>}</Link>)}</div></div></div>;
}
function State({ children }: { children: React.ReactNode }) { return <div className="rounded-2xl border bg-white p-10 text-center text-sm text-slate-500">{children}</div>; }
