"use client";

import { useEffect, useState } from "react";
import { FormProvider, useForm, useFormContext } from "react-hook-form";
import { useRouter } from "next/navigation";
import { Building2, ChevronLeft, ChevronRight, ImagePlus, Loader2, ShieldCheck } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { useProperties } from "@/hooks/use-properties";
import { propertyImageApi } from "@/lib/api/property-image-api";
import type { PropertyInput } from "@/lib/api/api-types";
import { getApiErrorMessage } from "@/lib/api/api-error";
import { toast } from "sonner";

type FormValues = { name: string; publicArea: string; approximateAddress: string; exactAddress: string; latitude: string; longitude: string; entranceLatitude: string; entranceLongitude: string; accessInstructions: string; visitorIdentificationRequired: boolean; vehicleHeightLimitCm: string; entryCutoffLocalTime: string; generalParkingRules: string; commonSafetyRules: string };
const defaults: FormValues = { name: "", publicArea: "", approximateAddress: "", exactAddress: "", latitude: "", longitude: "", entranceLatitude: "", entranceLongitude: "", accessInstructions: "", visitorIdentificationRequired: false, vehicleHeightLimitCm: "", entryCutoffLocalTime: "", generalParkingRules: "", commonSafetyRules: "" };

export function PropertyWizardLiveView() {
  const methods = useForm<FormValues>({ defaultValues: defaults, mode: "onBlur" }); const { create } = useProperties(); const router = useRouter(); const [step, setStep] = useState(1); const [files, setFiles] = useState<File[]>([]); const [error, setError] = useState(""); const [submitting, setSubmitting] = useState(false); const pending = create.isPending || submitting;
  useEffect(() => { const warn = (event: BeforeUnloadEvent) => { if (methods.formState.isDirty || files.length) event.preventDefault(); }; window.addEventListener("beforeunload", warn); return () => window.removeEventListener("beforeunload", warn); }, [files.length, methods.formState.isDirty]);
  async function next() { const fields: Array<keyof FormValues> = step === 1 ? ["name", "publicArea", "approximateAddress", "exactAddress"] : ["latitude", "longitude"]; if (await methods.trigger(fields)) setStep((value) => Math.min(3, value + 1)); }
  async function submit(values: FormValues) { if (pending) return; setError(""); const latitude = Number(values.latitude); const longitude = Number(values.longitude); if (!Number.isFinite(latitude) || !Number.isFinite(longitude)) { setError("Valid latitude and longitude are required."); setStep(2); return; } const payload: PropertyInput = { name: values.name.trim(), publicArea: values.publicArea.trim(), approximateAddress: values.approximateAddress.trim(), exactAddress: values.exactAddress.trim(), latitude, longitude, ...(values.entranceLatitude && values.entranceLongitude ? { entranceLatitude: Number(values.entranceLatitude), entranceLongitude: Number(values.entranceLongitude) } : {}), ...(values.accessInstructions.trim() ? { accessInstructions: values.accessInstructions.trim() } : {}), visitorIdentificationRequired: values.visitorIdentificationRequired, ...(values.vehicleHeightLimitCm ? { vehicleHeightLimitCm: Number(values.vehicleHeightLimitCm) } : {}), ...(values.entryCutoffLocalTime ? { entryCutoffLocalTime: values.entryCutoffLocalTime } : {}), ...(values.generalParkingRules.trim() ? { generalParkingRules: values.generalParkingRules.trim() } : {}), ...(values.commonSafetyRules.trim() ? { commonSafetyRules: values.commonSafetyRules.trim() } : {}) }; setSubmitting(true); try { const property = await create.mutateAsync(payload); if (files.length) { try { await propertyImageApi.upload(property.id, files); } catch (uploadError) { toast.error(`Property created, but images were not uploaded: ${getApiErrorMessage(uploadError)}`); } } methods.reset(); setFiles([]); router.push(`/owner/properties/${property.id}`); } catch (requestError) { setError(getApiErrorMessage(requestError)); } finally { setSubmitting(false); } }
  function chooseFiles(list: FileList | null) { if (!list) return; const selected = Array.from(list); const invalid = selected.find((file) => !["image/jpeg", "image/png", "image/webp"].includes(file.type) || file.size > 5 * 1024 * 1024); if (invalid) { setError("Images must be JPEG, PNG, or WebP and no larger than 5 MB each."); return; } if (selected.length > 10) { setError("A Property can have at most 10 images."); return; } setError(""); setFiles(selected); }
  return <FormProvider {...methods}><main className="min-h-screen bg-[#f9f9ff] px-4 py-8"><form onSubmit={methods.handleSubmit(submit)} className="mx-auto max-w-4xl space-y-6"><header className="rounded-2xl border bg-white p-6"><div className="flex items-center gap-3"><span className="flex size-11 items-center justify-center rounded-xl bg-[#064E3B] text-white"><Building2 className="size-5" /></span><div><p className="text-xs font-bold uppercase tracking-wider text-emerald-700">Property setup · Step {step} of 3</p><h1 className="text-2xl font-extrabold">Add a Property</h1></div></div><div className="mt-5 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full bg-[#064E3B] transition-all" style={{ width: `${step / 3 * 100}%` }} /></div></header>{step === 1 && <IdentityFields />}{step === 2 && <OperationsFields />}{step === 3 && <ReviewAndImages files={files} chooseFiles={chooseFiles} />}{error && <p role="alert" className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm font-semibold text-red-700">{error}</p>}<footer className="flex flex-col-reverse justify-between gap-3 rounded-2xl border bg-white p-4 sm:flex-row"><Button type="button" variant="outline" disabled={step === 1 || pending} onClick={() => setStep((value) => Math.max(1, value - 1))}><ChevronLeft className="size-4" />Back</Button>{step < 3 ? <Button type="button" className="bg-[#064E3B]" onClick={next}>Continue<ChevronRight className="size-4" /></Button> : <Button type="submit" className="bg-[#064E3B]" disabled={pending} aria-busy={pending}>{pending ? <><Loader2 className="size-4 animate-spin" />Creating…</> : "Create Property"}</Button>}</footer></form></main></FormProvider>;
}

function Field({ name, label, required = false, type = "text", min, max }: { name: keyof FormValues; label: string; required?: boolean; type?: string; min?: number; max?: number }) { const { register, formState: { errors } } = useFormContext<FormValues>(); return <div className="space-y-2"><Label htmlFor={name}>{label}</Label><Input id={name} type={type} step={type === "number" ? "any" : undefined} min={min} max={max} {...register(name, { required: required ? `${label} is required` : false })} aria-invalid={Boolean(errors[name])} />{errors[name] && <p role="alert" className="text-xs text-red-700">{String(errors[name]?.message)}</p>}</div>; }
function IdentityFields() { return <section className="grid gap-5 rounded-2xl border bg-white p-6 sm:grid-cols-2"><Field name="name" label="Property name" required /><Field name="publicArea" label="Public area" required /><Field name="approximateAddress" label="Approximate public address" required /><Field name="exactAddress" label="Exact private address" required /><p className="text-xs text-muted-foreground sm:col-span-2">The exact address is encrypted by the backend and is only available in authorized private views.</p></section>; }
function OperationsFields() { const { register } = useFormContext<FormValues>(); return <section className="grid gap-5 rounded-2xl border bg-white p-6 sm:grid-cols-2"><Field name="latitude" label="Latitude" type="number" min={-90} max={90} required /><Field name="longitude" label="Longitude" type="number" min={-180} max={180} required /><Field name="entranceLatitude" label="Entrance latitude (optional)" type="number" min={-90} max={90} /><Field name="entranceLongitude" label="Entrance longitude (optional)" type="number" min={-180} max={180} /><Field name="vehicleHeightLimitCm" label="Vehicle height limit (cm)" type="number" min={1} max={1000} /><Field name="entryCutoffLocalTime" label="Entry cutoff" type="time" /><div className="space-y-2 sm:col-span-2"><Label htmlFor="accessInstructions">Private access instructions</Label><Textarea id="accessInstructions" {...register("accessInstructions")} /></div><div className="space-y-2"><Label htmlFor="generalParkingRules">General parking rules</Label><Textarea id="generalParkingRules" {...register("generalParkingRules")} /></div><div className="space-y-2"><Label htmlFor="commonSafetyRules">Common safety rules</Label><Textarea id="commonSafetyRules" {...register("commonSafetyRules")} /></div><label className="flex items-center gap-2 text-sm font-semibold sm:col-span-2"><input type="checkbox" {...register("visitorIdentificationRequired")} />Visitor identification required</label></section>; }
function ReviewAndImages({ files, chooseFiles }: { files: File[]; chooseFiles: (files: FileList | null) => void }) { return <div className="space-y-5"><section className="rounded-2xl border bg-white p-6"><h2 className="flex items-center gap-2 font-bold"><ImagePlus className="size-5 text-emerald-700" />Property images</h2><label className="mt-4 flex cursor-pointer flex-col items-center rounded-xl border-2 border-dashed p-8 text-center"><input className="sr-only" type="file" accept="image/jpeg,image/png,image/webp" multiple onChange={(event) => chooseFiles(event.target.files)} /><span className="font-semibold">Choose or drop up to 10 images</span><span className="mt-1 text-xs text-muted-foreground">JPEG, PNG or WebP · maximum 5 MB each</span></label>{files.length > 0 && <ul className="mt-3 space-y-1 text-xs text-slate-600">{files.map((file) => <li key={`${file.name}-${file.size}`}>{file.name} · {(file.size / 1024 / 1024).toFixed(1)} MB</li>)}</ul>}</section><section className="rounded-2xl border border-blue-200 bg-blue-50 p-5"><h2 className="flex items-center gap-2 font-bold text-blue-950"><ShieldCheck className="size-5" />Backend capability boundary</h2><p className="mt-2 text-sm text-blue-900">This submission saves only Property identity, location, rules, and images. Parking spaces, pricing, availability, deposits, peak pricing, amenities, and QR/OTP settings remain future prototypes and are not sent to the server.</p></section></div>; }
