ALTER TYPE "platform_fee_rule_status" ADD VALUE IF NOT EXISTS 'DRAFT';
ALTER TYPE "platform_fee_rule_status" ADD VALUE IF NOT EXISTS 'SCHEDULED';
ALTER TYPE "platform_fee_rule_status" ADD VALUE IF NOT EXISTS 'ARCHIVED';

ALTER TYPE "domain_audit_event_type" ADD VALUE IF NOT EXISTS 'PLATFORM_FEE_CREATED';
ALTER TYPE "domain_audit_event_type" ADD VALUE IF NOT EXISTS 'PLATFORM_FEE_ACTIVATED';
ALTER TYPE "domain_audit_event_type" ADD VALUE IF NOT EXISTS 'PLATFORM_FEE_DEACTIVATED';
ALTER TYPE "domain_audit_event_type" ADD VALUE IF NOT EXISTS 'PLATFORM_FEE_ARCHIVED';
