"use client";

import { use, useState } from "react";
import Link from "next/link";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { ArrowLeft, CheckCircle2, Loader2, MapPin, ShieldCheck, XCircle } from "lucide-react";
import { adminApi } from "@/lib/api/admin-api";
import { queryKeys } from "@/lib/query-keys";
import { getApiErrorMessage } from "@/lib/api/api-error";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import Image from "next/image";

export default function AdminPropertyDetailPage({ params }: { params: Promise<{ propertyId: string }> }) {
  const { propertyId } = use(params); const client = useQueryClient(); const [decision, setDecision] = useState<"APPROVE" | "REJECT" | null>(null); const [reason, setReason] = useState(""); const [message, setMessage] = useState("");
  const query = useQuery({ queryKey: queryKeys.adminProperties.detail(propertyId), queryFn: () => adminApi.propertyDetail(propertyId) });
  const mutation = useMutation({ mutationFn: () => adminApi.verifyProperty(propertyId, decision === "REJECT" ? { decision, reason } : { decision: "APPROVE" }), onSuccess: async () => { setMessage(`Property ${decision === "APPROVE" ? "approved" : "rejected"} successfully.`); setDecision(null); setReason(""); await client.invalidateQueries({ queryKey: queryKeys.adminProperties.pendingRoot }); await query.refetch(); } });
  if (query.isPending) return <div className="py-24 text-center"><Loader2 className="mx-auto size-7 animate-spin" /></div>;
  if (query.isError || !query.data) return <div className="rounded-2xl border bg-white p-8"><p className="text-red-700">{getApiErrorMessage(query.error)}</p></div>;
  const property = query.data;
  return <div className="space-y-6"><Link href="/admin/properties/pending" className="inline-flex items-center gap-2 text-sm font-semibold text-slate-600 hover:text-[#064E3B]"><ArrowLeft className="size-4" />Back to queue</Link><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-start"><div><p className="text-xs font-bold uppercase tracking-wider text-emerald-700">Private admin review</p><h1 className="mt-2 text-3xl font-extrabold">{property.name}</h1><p className="mt-2 flex items-center gap-2 text-sm text-muted-foreground"><MapPin className="size-4" />{property.exactAddress}</p></div><span className="w-fit rounded-full bg-amber-100 px-3 py-1 text-xs font-bold text-amber-800">{property.verificationStatus}</span></div>
    {message && <div role="status" className="rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm font-semibold text-emerald-800">{message}</div>}
    <div className="grid gap-5 lg:grid-cols-3"><section className="space-y-5 rounded-2xl border bg-white p-6 lg:col-span-2"><h2 className="text-lg font-bold">Property information</h2><Info label="Public area" value={property.publicArea} /><Info label="Approximate public address" value={property.approximateAddress} /><Info label="Exact address (admin only)" value={property.exactAddress} /><Info label="Coordinates" value={`${property.latitude}, ${property.longitude}`} /><Info label="Access instructions" value={property.accessInstructions ?? "Not provided"} /><div><h3 className="text-xs font-bold uppercase tracking-wider text-slate-500">Submitted by</h3><p className="mt-1 text-sm">{property.creator.fullName} · {property.creator.email} · {property.creator.phone}</p></div><div className="grid gap-3 sm:grid-cols-2">{property.images.map((image, index) => <div key={image.id} className="relative aspect-[4/3] overflow-hidden rounded-xl bg-slate-100"><Image src={image.url} alt={`Verification image ${index + 1}`} fill sizes="(max-width: 640px) 100vw, 50vw" className="object-cover" />{image.isCover && <span className="absolute left-2 top-2 rounded bg-black/70 px-2 py-1 text-[10px] font-bold text-white">Cover</span>}</div>)}</div>{property.images.length === 0 && <p className="rounded-xl bg-amber-50 p-4 text-sm text-amber-800">No images uploaded. Approval requirements will not be met.</p>}</section><aside className="h-fit space-y-4 rounded-2xl border bg-white p-6"><div className="flex items-center gap-2"><ShieldCheck className="size-5 text-[#064E3B]" /><h2 className="font-bold">Verification decision</h2></div><Button className="w-full bg-[#064E3B]" disabled={property.verificationStatus !== "PENDING"} onClick={() => setDecision("APPROVE")}><CheckCircle2 className="size-4" />Approve property</Button><Button className="w-full" variant="outline" disabled={property.verificationStatus !== "PENDING"} onClick={() => setDecision("REJECT")}><XCircle className="size-4" />Reject property</Button>{decision === "REJECT" && <Textarea aria-label="Rejection reason" value={reason} onChange={(event) => setReason(event.target.value)} placeholder="Provide a clear reason (minimum 10 characters)" />}{decision && <div className="flex gap-2"><Button variant="ghost" disabled={mutation.isPending} onClick={() => setDecision(null)}>Cancel</Button><Button disabled={mutation.isPending || (decision === "REJECT" && reason.trim().length < 10)} onClick={() => mutation.mutate()}>{mutation.isPending ? <Loader2 className="size-4 animate-spin" /> : "Confirm"}</Button></div>}{mutation.isError && <p role="alert" className="text-xs text-red-700">{getApiErrorMessage(mutation.error)}</p>}</aside></div></div>;
}
function Info({ label, value }: { label: string; value: string }) { return <div><dt className="text-xs font-bold uppercase tracking-wider text-slate-500">{label}</dt><dd className="mt-1 text-sm leading-relaxed text-slate-800">{value}</dd></div>; }
