"use client";
import { use, useRef, useState } from "react";
import Link from "next/link";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { ArrowLeft, Loader2 } from "lucide-react";
import { toast } from "sonner";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from "@/components/ui/alert-dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { bookingsApi } from "@/lib/api/bookings-api";
import { getApiErrorMessage } from "@/lib/api/api-error";
import { formatBDTFromPaisa, formatDateTime, vehicleLabels } from "@/lib/formatters";
import { bookingStatus, paymentStatus } from "@/lib/marketplace-status";
import { queryKeys } from "@/lib/query-keys";

export default function BookingDetailsPage({ params }: { params: Promise<{ bookingId: string }> }) {
  const { bookingId } = use(params); const client = useQueryClient(); const [confirmCancel, setConfirmCancel] = useState(false);
  const query = useQuery({ queryKey: queryKeys.bookings.detail(bookingId), queryFn: () => bookingsApi.driverDetail(bookingId), refetchInterval: 30_000 });
  const refresh = async () => { await Promise.all([query.refetch(), client.invalidateQueries({ queryKey: queryKeys.bookings.root }), client.invalidateQueries({ queryKey: queryKeys.wallet.current })]); };
  const cancel = useMutation({ mutationFn: () => bookingsApi.cancel(bookingId), onSuccess: async () => { toast.success("Booking cancelled"); setConfirmCancel(false); await refresh(); }, onError: (error) => toast.error(getApiErrorMessage(error)) });
  const checkout = useMutation({ mutationFn: () => bookingsApi.requestCheckout(bookingId), onSuccess: async () => { toast.success("Checkout requested"); await refresh(); }, onError: (error) => toast.error(getApiErrorMessage(error)) });
  if (query.isPending) return <State text="Loading booking" loading />; if (query.isError) return <State text={getApiErrorMessage(query.error)} />;
  const booking = query.data; const status = bookingStatus[booking.status]; const payment = booking.payments?.[0];
  return <div className="mx-auto max-w-5xl space-y-6 px-4 sm:px-6"><Link href="/driver/bookings" className="inline-flex items-center gap-2 text-sm font-semibold text-slate-600"><ArrowLeft className="size-4" />My bookings</Link><div className="flex flex-col justify-between gap-3 sm:flex-row"><div><div className="flex items-center gap-2"><h1 className="font-mono text-2xl font-extrabold">{booking.bookingCode}</h1><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${status.className}`}>{status.label}</span></div><p className="mt-2 text-sm text-slate-500">Created {formatDateTime(booking.createdAt)}</p></div><div className="flex flex-wrap gap-2">{booking.status === "PAYMENT_PENDING" && <Link href={`/driver/bookings/${booking.id}/payment`}><Button>Complete payment</Button></Link>}{["PAYMENT_PENDING", "CONFIRMED"].includes(booking.status) && <Button variant="destructive" onClick={() => setConfirmCancel(true)}>Cancel booking</Button>}{booking.status === "CHECKED_IN" && <Button disabled={checkout.isPending} onClick={() => checkout.mutate()}>Request checkout</Button>}{booking.status === "COMPLETED" && <><Link href={`/driver/bookings/${booking.id}/review`}><Button variant="outline">Write review</Button></Link><Link href={`/driver/bookings/${booking.id}/dispute`}><Button variant="outline">Open dispute</Button></Link></>}</div></div>
    <div className="grid gap-5 lg:grid-cols-3"><section className="space-y-4 rounded-lg border bg-white p-6 lg:col-span-2"><h2 className="font-bold">Reservation</h2><Info label="Property" value={booking.property?.name ?? "Property"} /><Info label="Public address" value={booking.property?.approximateAddress ?? "Not available"} /><Info label="Parking" value={booking.parkingSpot?.resourceType === "SHARED_POOL" ? "Shared Parking Area" : booking.assignedUnitCode ? `${booking.parkingSpot?.displayName ?? "Fixed parking"} · Unit ${booking.assignedUnitCode}` : booking.parkingSpot?.displayName ?? booking.parkingSpot?.spotCode ?? "Fixed space"} /><Info label="Vehicle" value={`${booking.vehicle?.registrationNumber ?? ""} · ${booking.vehicle ? vehicleLabels[booking.vehicle.vehicleType] : ""}`} /><Info label="Starts" value={formatDateTime(booking.startAt)} /><Info label="Scheduled end" value={formatDateTime(booking.scheduledEndAt)} />{booking.checkedInAt && <Info label="Checked in" value={formatDateTime(booking.checkedInAt)} />}{booking.checkedOutAt && <Info label="Checked out" value={formatDateTime(booking.checkedOutAt)} />}</section><aside className="h-fit space-y-3 rounded-lg border bg-white p-6"><h2 className="font-bold">Payment</h2><Price label="Parking" value={booking.baseAmountPaisa} /><Price label="Platform fee" value={booking.platformFeePaisa} /><Price label="Deposit" value={booking.depositPaisa} /><Price label="Total" value={booking.totalAmountPaisa} strong />{payment && <span className={`inline-flex rounded-full px-2 py-1 text-xs font-bold ${paymentStatus[payment.status].className}`}>{paymentStatus[payment.status].label}</span>}</aside></div>
    {payment && ["CAPTURED", "PARTIALLY_REFUNDED"].includes(payment.status) && <RefundForm paymentId={payment.id} maximum={payment.amountPaisa} onDone={refresh} />}
    <AlertDialog open={confirmCancel} onOpenChange={setConfirmCancel}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Cancel this booking?</AlertDialogTitle><AlertDialogDescription>Availability will be released. Any refund is calculated and processed only by backend policy.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Keep booking</AlertDialogCancel><AlertDialogAction variant="destructive" disabled={cancel.isPending} onClick={() => cancel.mutate()}>{cancel.isPending && <Loader2 className="size-4 animate-spin" />}Cancel booking</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
  </div>;
}
function RefundForm({ paymentId, maximum, onDone }: { paymentId: string; maximum: string; onDone: () => Promise<void> }) { const [amount, setAmount] = useState(""); const [reason, setReason] = useState(""); const [confirmRefund, setConfirmRefund] = useState(false); const idempotencyKey = useRef(crypto.randomUUID()); const mutation = useMutation({ mutationFn: () => bookingsApi.refund(paymentId, { amountPaisa: String(Math.round(Number(amount) * 100)), reason, idempotencyKey: idempotencyKey.current }), onSuccess: async () => { toast.success("Refund processed"); setConfirmRefund(false); setAmount(""); setReason(""); idempotencyKey.current = crypto.randomUUID(); await onDone(); }, onError: (error) => toast.error(getApiErrorMessage(error)) }); return <section className="rounded-lg border bg-white p-6"><h2 className="font-bold">Request refund</h2><p className="mt-1 text-xs text-slate-500">Maximum payment amount {formatBDTFromPaisa(maximum)}. The server enforces the remaining refundable balance.</p><div className="mt-4 grid gap-3 sm:grid-cols-[10rem_1fr_auto]"><Input aria-label="Refund amount in BDT" type="number" min="0.01" step="0.01" placeholder="Amount BDT" value={amount} onChange={(event) => setAmount(event.target.value)} /><Input aria-label="Refund reason" minLength={5} maxLength={500} placeholder="Reason" value={reason} onChange={(event) => setReason(event.target.value)} /><Button disabled={mutation.isPending || !amount || reason.trim().length < 5} onClick={() => setConfirmRefund(true)}>Request refund</Button></div><AlertDialog open={confirmRefund} onOpenChange={setConfirmRefund}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Request this refund?</AlertDialogTitle><AlertDialogDescription>You are requesting {amount ? formatBDTFromPaisa(String(Math.round(Number(amount) * 100))) : "a refund"}. The backend will enforce eligibility and the remaining refundable amount.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Cancel</AlertDialogCancel><AlertDialogAction variant="destructive" disabled={mutation.isPending} onClick={() => mutation.mutate()}>{mutation.isPending&&<Loader2 className="size-4 animate-spin"/>}Confirm refund</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></section>; }
function Info({ label, value }: { label: string; value: string }) { return <div><dt className="text-xs font-bold uppercase text-slate-500">{label}</dt><dd className="mt-1 text-sm">{value}</dd></div>; }
function Price({ label, value, strong }: { label: string; value: string; strong?: boolean }) { return <div className={`flex justify-between text-sm ${strong ? "border-t pt-3 font-bold" : ""}`}><span>{label}</span><span>{formatBDTFromPaisa(value)}</span></div>; }
function State({ text, loading }: { text: string; loading?: boolean }) { return <div className="py-24 text-center">{loading && <Loader2 className="mx-auto mb-3 size-6 animate-spin" />}<p>{text}</p></div>; }
