export interface ApiErrorPayload {
  code?: string;
  message?: string;
  details?: unknown;
}

export class ApiError extends Error {
  constructor(
    message: string,
    public readonly status: number,
    public readonly code = "UNKNOWN_ERROR",
    public readonly requestId?: string,
    public readonly details?: unknown,
  ) {
    super(message);
    this.name = "ApiError";
  }
}

const FRIENDLY_MESSAGES: Record<string, string> = {
  AUTH_REQUIRED: "Please sign in to continue.",
  AUTH_UNAUTHORIZED: "Your session has expired. Please sign in again.",
  AUTH_FORBIDDEN: "You do not have permission to perform this action.",
  AUTH_INVALID_CREDENTIALS: "The current password or sign-in details are incorrect.",
  AUTH_PASSWORD_RESET_TOKEN_INVALID: "This reset link is invalid, expired, or has already been used.",
  AUTH_NEW_PASSWORD_MUST_DIFFER: "Choose a password different from your current password.",
  AUTH_SESSION_NOT_FOUND: "That session is no longer active.",
  EMAIL_OR_PHONE_ALREADY_REGISTERED: "An account already uses this email or phone. Use the existing-account invitation flow.",
  VEHICLE_NOT_FOUND: "That vehicle could not be found.",
  VEHICLE_REGISTRATION_CONFLICT: "A vehicle with this registration is already registered.",
  VEHICLE_DELETE_BLOCKED: "This vehicle cannot be deleted in its current state.",
  PROPERTY_NOT_FOUND: "That property could not be found.",
  PROPERTY_INVALID_STATE: "This property cannot be changed in its current state.",
  PROPERTY_DELETE_BLOCKED: "Remove property images and finish active Guard dependencies before deleting this property.",
  PROPERTY_VERSION_CONFLICT: "This property changed since you opened it. Reload and try again.",
  PROPERTY_IMAGE_LIMIT_EXCEEDED: "A property can have at most 10 images.",
  PROPERTY_IMAGE_REQUIRED: "Choose at least one property image.",
  PROPERTY_IMAGE_INVALID_TYPE: "Only JPEG, PNG, and WebP images are supported.",
  PROPERTY_IMAGE_TOO_LARGE: "Each property image must be 5 MB or smaller.",
  PROPERTY_IMAGE_NOT_FOUND: "That property image no longer exists.",
  PROPERTY_IMAGE_UPLOAD_FAILED: "Image storage is temporarily unavailable. Please retry.",
  PROPERTY_IMAGE_DELETE_FAILED: "The image could not be removed from storage.",
  PROPERTY_VERIFICATION_CONFLICT: "This property was reviewed by someone else. Refresh and try again.",
  PROPERTY_VERIFICATION_REQUIREMENTS_NOT_MET: "Approval requires valid property details and at least one image.",
  GUARD_ASSIGNMENT_ALREADY_EXISTS: "This guard already has an active assignment.",
  GUARD_ASSIGNMENT_STATE_CONFLICT: "The assignment state changed. Refresh and try again.",
  GUARD_ASSIGNMENT_NOT_FOUND: "That Guard assignment could not be found.",
  GUARD_ASSIGNMENT_INVALID_TRANSITION: "That Guard assignment action is not allowed in its current state.",
  PROPERTY_GUARD_MEMBERSHIP_ALREADY_EXISTS: "This Guard already belongs to the property Guard pool.",
  PROPERTY_GUARD_MEMBERSHIP_NOT_ACTIVE: "The Guard must accept the property invitation before a shift can be assigned.",
  ELIGIBLE_MANAGER_NOT_FOUND: "No eligible Manager account was found for that email or phone.",
  MANAGER_DELEGATION_CONFLICT: "This Manager already has a current delegation for the selected Provider scope.",
  MANAGER_DELEGATION_RESOURCE_INVALID: "One or more selected parking resources are outside your Property scope.",
  MANAGER_DELEGATION_PERMISSION_REQUIRED: "This Manager delegation does not grant the required permission.",
  MANAGER_DELEGATION_INVALID_TRANSITION: "This Manager invitation can no longer be changed in its current state.",
  PARKING_RESOURCE_NOT_FOUND: "That parking resource could not be found.",
  PARKING_RESOURCE_CODE_CONFLICT: "That spot code is already used at this Property.",
  PARKING_RESOURCE_CAPACITY_INVALID: "The requested capacity is not valid for this resource type.",
  PARKING_RESOURCE_CAPACITY_IN_USE: "Capacity cannot be reduced below the verified parking-right entitlement.",
  PARKING_RESOURCE_DELETE_BLOCKED: "This resource has an unfinished booking and cannot be deleted.",
  PARKING_RESOURCE_NOT_LISTABLE: "This parking resource is not eligible for a commercial listing.",
  PARKING_RIGHT_NOT_FOUND: "That parking right could not be found.",
  PARKING_RIGHT_NOT_LISTABLE: "This parking right is not currently eligible for commercial listing.",
  PARKING_RIGHT_COMMERCIAL_USE_FORBIDDEN: "A use-only right cannot be used commercially.",
  PARKING_RIGHT_CONFLICT: "This parking-right claim conflicts with an existing entitlement.",
  PARKING_RIGHT_CAPACITY_EXCEEDED: "The claimed quantity exceeds this parking resource's capacity.",
  PARKING_RIGHT_FORBIDDEN: "You do not control this parking right.",
  PARKING_RIGHT_INVALID: "This parking-right claim is not valid.",
  PARKING_RIGHT_PRICE_FORBIDDEN: "This right does not allow pricing the parking resource.",
  PARKING_RIGHT_QUANTITY_INVALID: "The parking-right quantity is not valid.",
  PARKING_LISTING_NOT_FOUND: "That listing could not be found.",
  PARKING_LISTING_CONFLICT: "A conflicting listing already exists for this parking resource.",
  PARKING_LISTING_NOT_ELIGIBLE: "The listing cannot be activated until its Property, resource, and commercial right are eligible.",
  PARKING_LISTING_AVAILABILITY_REQUIRED: "Set weekly availability for this parking resource before activating the listing.",
  PARKING_LISTING_STATE_INVALID: "That listing action is not allowed in its current state.",
  PARKING_LISTING_NOT_AVAILABLE: "This parking offer is no longer available.",
  LISTING_DURATION_INVALID: "The listing's minimum and maximum duration are not valid.",
  LISTING_VEHICLE_TYPE_UNSUPPORTED: "The listing includes a vehicle type the parking resource does not support.",
  VEHICLE_NOT_COMPATIBLE: "The selected vehicle is not compatible with this parking offer.",
  BOOKING_DURATION_INVALID: "The selected duration is outside this offer's booking limits.",
  QUOTE_START_IN_PAST: "Choose a parking start time in the future.",
  BOOKING_QUOTE_EXPIRED: "Price quote expired. Refresh the quote.",
  BOOKING_QUOTE_NOT_FOUND: "That price quote could not be found.",
  PARKING_NOT_AVAILABLE: "Someone else reserved this parking just before you. Please choose another option.",
  RESERVATION_HOLD_EXPIRED: "Your reservation hold expired. Please create a new quote and try again.",
  RESERVATION_HOLD_NOT_FOUND: "That reservation hold could not be found.",
  RESERVATION_HOLD_CONSUMED: "This reservation hold has already been used.",
  BOOKING_NOT_FOUND: "That booking could not be found.",
  BOOKING_TRANSITION_INVALID: "This booking action is not allowed in its current state.",
  BOOKING_CANCELLATION_WINDOW_CLOSED: "This booking has already started and can no longer be cancelled.",
  PAYMENT_NOT_REFUNDABLE: "This payment is not refundable in its current state.",
  PAYMENT_NOT_FOUND: "That payment could not be found.",
  REFUND_AMOUNT_EXCEEDED: "The amount exceeds the remaining refundable balance.",
  REFUND_BALANCE_UNAVAILABLE: "The Provider balance is currently insufficient for this refund.",
  REFUND_FORBIDDEN: "You are not allowed to refund this payment.",
  ACCESS_CREDENTIAL_INVALID: "This access credential is invalid, used, or expired.",
  GUARD_BOOKING_FORBIDDEN: "You are not assigned to this Provider at this Property.",
  BOOKING_CHECK_IN_WINDOW_INVALID: "This booking is outside the permitted check-in window.",
  PAYOUT_BALANCE_INSUFFICIENT: "Available balance is insufficient for this payout request.",
  PAYOUT_TRANSITION_INVALID: "That payout action is not allowed in its current state.",
  PAYOUT_NOT_FOUND: "That payout request could not be found.",
  REVIEW_ALREADY_EXISTS: "This booking has already been reviewed.",
  REVIEW_BOOKING_NOT_COMPLETED: "Only completed bookings can be reviewed.",
  REVIEW_NOT_FOUND: "That review could not be found.",
  DISPUTE_ALREADY_EXISTS: "A dispute already exists for this booking.",
  DISPUTE_STATE_INVALID: "This dispute has already been resolved.",
  DISPUTE_FORBIDDEN: "You are not allowed to open a dispute for this booking.",
  DISPUTE_NOT_FOUND: "That dispute could not be found.",
  IDEMPOTENCY_KEY_REUSED: "This request key was already used for different data. Please retry the action.",
  MARKETPLACE_FORBIDDEN: "You do not have permission for this marketplace action.",
  WALLET_NOT_FOUND: "A wallet has not been configured for this account.",
  SETTLEMENT_WALLET_UNAVAILABLE: "The Provider settlement wallet is unavailable.",
};

export function getApiErrorMessage(error: unknown): string {
  if (error instanceof ApiError) return FRIENDLY_MESSAGES[error.code] ?? error.message;
  return "Something went wrong. Please try again.";
}
