export const queryKeys = {
  auth: { me: ["auth", "me"] as const, sessions: ["auth", "sessions"] as const },
  vehicles: { all: ["vehicles"] as const, detail: (id: string) => ["vehicles", id] as const },
  properties: { all: (filters: object = {}) => ["properties", filters] as const, root: ["properties"] as const, detail: (id: string) => ["properties", "detail", id] as const },
  propertyImages: { byProperty: (id: string) => ["property-images", id] as const },
  propertyGuards: { byProperty: (id: string) => ["property-guards", id] as const },
  ownerGuardAssignments: { all: (filters: object = {}) => ["guard-assignments", "provider", filters] as const, root: ["guard-assignments", "provider"] as const, detail: (id: string) => ["guard-assignments", "provider", id] as const },
  guardMemberships: { all: (filters: object = {}) => ["guard-memberships", filters] as const, root: ["guard-memberships"] as const },
  guardAssignments: { all: (filters: object = {}) => ["guard-assignments", "guard", filters] as const, root: ["guard-assignments", "guard"] as const, detail: (id: string) => ["guard-assignments", "guard", id] as const },
  adminProperties: { pending: (filters: { page: number; limit: number }) => ["admin", "properties", "pending", filters] as const, pendingRoot: ["admin", "properties", "pending"] as const, detail: (id: string) => ["admin", "properties", id] as const },
  managerDelegations: { provider: ["manager-delegations", "provider"] as const, manager: ["manager-delegations", "manager"] as const },
  parkingResources: { root: ["parking-resources"] as const, byProperty: (propertyId: string) => ["parking-resources", "property", propertyId] as const, detail: (resourceId: string) => ["parking-resources", "detail", resourceId] as const },
  parkingRights: { root: ["parking-rights"] as const, all: (filters: object = {}) => ["parking-rights", filters] as const, detail: (rightId: string) => ["parking-rights", "detail", rightId] as const },
  listings: { root: ["listings"] as const, all: (filters: object = {}) => ["listings", filters] as const, detail: (listingId: string) => ["listings", "detail", listingId] as const },
  availability: { root: ["availability"] as const, byResource: (resourceId: string) => ["availability", resourceId] as const },
  parkingSearch: { root: ["parking-search"] as const, results: (params: object) => ["parking-search", params] as const, property: (id: string, params: object) => ["parking-search", "property", id, params] as const },
  quotes: { detail: (quoteId: string) => ["quotes", quoteId] as const },
  holds: { detail: (holdId: string) => ["holds", holdId] as const },
  bookings: { root: ["bookings"] as const, driver: (filters: object = {}) => ["bookings", "driver", filters] as const, provider: (filters: object = {}) => ["bookings", "provider", filters] as const, providerDetail: (id: string) => ["bookings", "provider", "detail", id] as const, guard: (filters: object = {}) => ["bookings", "guard", filters] as const, detail: (id: string) => ["bookings", "detail", id] as const, guardDetail: (id: string) => ["bookings", "guard", "detail", id] as const },
  wallet: { current: ["wallet", "current"] as const, transactions: (filters: object = {}) => ["wallet", "transactions", filters] as const },
  earnings: { root: ["earnings"] as const, summary: (filters: object = {}) => ["earnings", "summary", filters] as const, transactions: (filters: object = {}) => ["earnings", "transactions", filters] as const },
  payouts: { root: ["payouts"] as const, provider: (filters: object = {}) => ["payouts", "provider", filters] as const, driver: (filters: object = {}) => ["payouts", "driver", filters] as const, detail: (id: string) => ["payouts", id] as const },
  refunds: { root: ["refunds"] as const, driver: (filters: object = {}) => ["refunds", "driver", filters] as const, detail: (id: string) => ["refunds", id] as const },
  disputes: { root: ["disputes"] as const, driver: (filters: object = {}) => ["disputes", "driver", filters] as const, provider: (filters: object = {}) => ["disputes", "provider", filters] as const, detail: (scope: string, id: string) => ["disputes", scope, id] as const },
  notifications: { root: ["notifications"] as const, all: (filters: object = {}) => ["notifications", filters] as const },
  driverDiscovery: {
    root: ["driver-discovery"] as const,
    favorites: ["driver-discovery", "favorites"] as const,
    savedLocations: ["driver-discovery", "saved-locations"] as const,
    recentSearches: ["driver-discovery", "recent-searches"] as const,
  },
  reviews: { root: ["reviews"] as const, driver: ["reviews", "driver"] as const, provider: (filters: object = {}) => ["reviews", "provider", filters] as const },
  adminMarketplace: { rights: (filters: object = {}) => ["admin", "marketplace", "rights", filters] as const, listings: (filters: object = {}) => ["admin", "marketplace", "listings", filters] as const, listing: (id: string) => ["admin", "marketplace", "listings", id] as const, payouts: (filters: object = {}) => ["admin", "marketplace", "payouts", filters] as const, disputes: (filters: object = {}) => ["admin", "marketplace", "disputes", filters] as const },
  admin: {
    dashboard: ["admin", "dashboard"] as const,
    users: { root: ["admin", "users"] as const, list: (filters: object = {}) => ["admin", "users", filters] as const, detail: (id: string) => ["admin", "users", "detail", id] as const },
    properties: { list: (filters: object = {}) => ["admin", "properties", "all", filters] as const, detail: (id: string) => ["admin", "properties", "detail", id] as const },
    resources: { list: (filters: object = {}) => ["admin", "resources", filters] as const },
    bookings: { list: (filters: object = {}) => ["admin", "bookings", filters] as const, detail: (id: string) => ["admin", "bookings", id] as const },
    sessions: { list: (filters: object = {}) => ["admin", "sessions", filters] as const },
    finance: { payments: (filters: object = {}) => ["admin", "payments", filters] as const, ledger: (filters: object = {}) => ["admin", "ledger", filters] as const, refunds: (filters: object = {}) => ["admin", "refunds", filters] as const, reconciliation: ["admin", "reconciliation"] as const, fees: (filters: object = {}) => ["admin", "platform-fees", filters] as const },
    trust: { riskFlags: (filters: object = {}) => ["admin", "risk-flags", filters] as const, reviews: (filters: object = {}) => ["admin", "reviews", filters] as const },
    analytics: { overview: (filters: object = {}) => ["admin", "analytics", "overview", filters] as const },
    audit: { list: (filters: object = {}) => ["admin", "audit", filters] as const },
    system: { health: ["admin", "system-health"] as const, capabilities: ["admin", "capabilities"] as const },
    content: { legal: ["admin", "content", "legal"] as const, articles: (filters: object = {}) => ["admin", "content", "articles", filters] as const },
    campaigns: { list: (filters: object = {}) => ["admin", "campaigns", filters] as const },
  },
};
