ALTER TYPE "domain_audit_event_type" ADD VALUE IF NOT EXISTS 'LEGAL_DOCUMENT_DRAFT_CREATED';
ALTER TYPE "domain_audit_event_type" ADD VALUE IF NOT EXISTS 'LEGAL_DOCUMENT_DRAFT_UPDATED';
ALTER TYPE "domain_audit_event_type" ADD VALUE IF NOT EXISTS 'LEGAL_DOCUMENT_ARCHIVED';
